;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ampl-insert-parens
	ampl-insert-sqbrackets
	backward-sexp
	c-electric-semi&comma
	crux-move-beginning-of-line
	dabbrev-expand
	forward-sexp
	indent-for-tab-command
	indent-pp-sexp
	kill-region
	kill-sexp
	mark-sexp
	markdown-exdent-or-delete
	org-beginning-of-line
	org-ctrl-c-ctrl-c
	org-cycle
	org-delete-char
	org-end-of-line
	org-kill-line
	org-self-insert-command
	org-todo
	org-yank
	paredit-backward
	paredit-backward-kill-word
	paredit-backward-up
	paredit-comment-dwim
	paredit-doublequote
	paredit-forward
	paredit-forward-delete
	paredit-kill
	paredit-meta-doublequote
	paredit-newline
	paredit-open-round
	paredit-raise-sexp
	paredit-reindent-defun
	paredit-semicolon
	paredit-splice-sexp
	paredit-wrap-round
	query-replace
	slime-autodoc-space
	slime-compile-defun
	transpose-sexps
	upcase-region
	))

(setq mc/cmds-to-run-once
      '(
	completion-at-point
	helm-M-x
	mouse-drag-mode-line
	))
