;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        indent-pp-sexp
        kill-sexp
        paredit-backward
        paredit-backward-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        ))
